export const NETWORK_TYPES = {
  LOAD_FOLLOWING: 'NETWORK_TYPES.LOAD_FOLLOWING',
  FOLLOW_USER: 'NETWORK_TYPES.FOLLOW_USER',
  UNFOLLOW_USER: 'NETWORK_TYPES.UNFOLLOW_USER',
  SOCKET_FOLLOW_USER: 'NETWORK_TYPES.SOCKET_FOLLOW_USER',
  SOCKET_UNFOLLOW_USER: 'NETWORK_TYPES.SOCKET_UNFOLLOW_USER'
}