export const MEETUPS_TYPES = {
  LOAD_MEETUPS: 'MEETUPS_TYPES.LOAD_MEETUPS',
  LOAD_MEETUP_BY_ID: 'MEETUPS_TYPES.LOAD_MEETUP_BY_ID',
  TOGGLE_MEETUP_JOIN: 'MEETUPS_TYPES.TOGGLE_MEETUP_JOIN',
  DELETE_MEETUP: 'MEETUPS_TYPES.DELETE_MEETUP',
  CREATE_MEETUP_REQUEST: 'MEETUPS_TYPES.CREATE_REQUEST',
  CREATE_MEETUP_SUCCESS: 'MEETUPS_TYPES.CREATE_SUCCESS',
  CREATE_MEETUP_FAIL: 'MEETUPS_TYPES.CREATE_FAIL',
  UPDATE_MEETUP_REQUEST: 'MEETUPS_TYPES.UPDATE_REQUEST',
  UPDATE_MEETUP_SUCCESS: 'MEETUPS_TYPES.UPDATE_SUCCESS',
  UPDATE_MEETUP_FAIL: 'MEETUPS_TYPES.UPDATE_FAIL',
  SET_FORM_INITIAL_DATA: 'MEETUPS_TYPES.SET_FORM_INITIAL_DATA',
  CLEAR_FORM: 'MEETUPS_TYPES.CLEAR_FORM'
}