export const REGISTRATION_TYPES = {
  REGISTRATION_REQUEST: "REGISTRATION_MODAL_TYPES.REGISTRATION_REQUEST",
  REGISTRATION_SUCCESS: "REGISTRATION_MODAL_TYPES.REGISTRATION_SUCCESS",
  REGISTRATION_FAIL: "REGISTRATION_MODAL_TYPES.REGISTRATION_FAIL",
};
