export const APP_TYPES = {
  TOGGLE_SIDEBAR: 'APP_TYPES.TOGGLE_SIDEBAR',
  APP_INITIALIZED: 'APP_TYPES.APP_INITIALIZED',
  SET_WINDOW_DIMENSIONS: 'APP_TYPES.SET_WINDOW_DIMENSIONS',
  SET_LOADING: 'APP_TYPES.SET_LOADING'
}